### ISSUE TITLE
konas compability fix

### ISSUE THREAD

**Issue by rolkoztm** [vaxerski/harakiri#10]
kiedy konas compability fix? prosze cie potrzeba mi tego XD

**Comment by vaxerski** [comment]
nigdy. nie używam konasa, nie mam jego kodu, nie wiem co jest problemem.

**Comment by master7720** [comment]
Konas is a bad client seppuku is a bad client harakiri is a bad client

**Comment by vaxerski** [comment]
> Konas is a bad client seppuku is a bad client harakiri is a bad client

literally nobody asked. You came to this repo just to post that, please reconsider your existence.

**Comment by rolkoztm** [comment]
> Konas is a bad client seppuku is a bad client harakiri is a bad client

so what client is good ? haha

**Comment by rolkoztm** [comment]
let me close it
