### ISSUE TITLE
HUGE CLIENT!!! EPIC SEPPUKU BASE

### ISSUE THREAD

**Issue by HAV0X1014** [vaxerski/harakiri#4]
too bad its a seppuku skid. next time just contribute to the main project instead of skidding shit. you couldnt even make an interesting name.

![IMG_20211210_141134](https://user-images.githubusercontent.com/73144620/147119078-be6b1bef-c1fa-49bb-a140-6e08822986bd.jpg)

**Comment by vaxerski** [comment]
Cool. I don't care about your opinion.

**Comment by HAV0X1014** [comment]
you care enough to reply. also pretty fucking sad how you wanted to sell your skid.

**Comment by vaxerski** [comment]
Selling it was a meme to get people hooked into. Some people actually used it and I never charged a penny.
