### ISSUE TITLE
MASSIVE fucking Seppuku skid (also you disagreed with the Seppuku Simp (HAV0X), and now you shall pay the price)

### ISSUE THREAD

**Issue by Wolfsurge** [vaxerski/harakiri#5]
stop skidding :trollface:

**Comment by vaxerski** [comment]
Where did I disagree? I don't care about your or havox's opinion. What I have done with this client would go against seppuku's mission, therefore it made no sense to contrib to the original project.

Open source means I can do whatever the hell I want to. If you disagree with forking stuff, you should not be allowed on the internet.

Stop spamming this repo. I don't care.

**Comment by Wolfsurge** [comment]
idk couldn't think of a better word. also I'm pretty sure you didn't credit seppuku originally, also I am not against forking. I was also half joking, you do whatever the fuck you want, but I am against using others' code and not crediting the author or not saying that it is using their code. I hope u have a great day :)

**Comment by vaxerski** [comment]
You know why I did not credit? Because all i did was a visibility change and a release push so people could download. After your comments, I did credit seppuku in the readme. Originally they werent because (news flash) the repo wss private.

**Comment by Wolfsurge** [comment]
cool, well, I personally didn't know the repo was private, and therefore couldn't judge it with that factor included. I have now concluded that what you are doing is completely fine and stuff, I was just saying that bc you didn't credit seppuku. I hope this client goes well for you.
